# Generated by Django 3.1 on 2020-08-18 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_entry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='_date_added',
            new_name='date_added',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='_topic',
            new_name='topic',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='_date_added',
            new_name='date_added',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='_text',
            new_name='text',
        ),
    ]
